import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createApp} from '../server/app.mjs';
const seed=JSON.parse(await readFile(new URL('../dist/data/content.json',import.meta.url),'utf8'));
async function setup(t,extra={}){
 const dir=await mkdtemp(path.join(os.tmpdir(),'les-test-'));
 const content=structuredClone(seed);content.privacy.ready=true;content.privacy.operator='Test operator';
 const app=await createApp({dataDir:dir,content,enabled:true,origins:'https://les.example',authorize:async req=>{if(req.headers.authorization!=='Bearer test-only')throw Object.assign(Error('Нет доступа'),{status:401});},...extra});
 await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));
 t.after(async()=>{await new Promise(resolve=>app.server.close(resolve));await rm(dir,{recursive:true,force:true});});
 const base='http://127.0.0.1:'+app.server.address().port;
 const request=(url,method='GET',body,headers={})=>fetch(base+url,{method,headers:{'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});
 return {app,request,dir};
}
function booking(){const date=new Date(Date.now()+86400000*7).toISOString().slice(0,10);return {program:seed.programs[0].id,venue:seed.venues[0].id,date,time:'12:00',name:'Тестовый посетитель',phone:'+7 999 000-00-00',people:20,comment:'Тест, не отправлять',consent:true,website:''};}
test('disabled intake is honest and stores nothing',async t=>{const {request,app}=await setup(t,{enabled:false});assert.equal((await (await request('/api/status')).json()).bookingsEnabled,false);assert.equal((await request('/api/bookings','POST',booking(),{'Idempotency-Key':'test-disabled-0001'})).status,503);assert.equal(app.state().bookings.length,0);});
test('validation, private records, idempotency and disk persistence',async t=>{const {request,app,dir}=await setup(t);const x=booking();assert.equal((await request('/api/admin/bookings')).status,401);assert.equal((await request('/api/bookings','POST',{...x,consent:false},{'Idempotency-Key':'test-consent-0001'})).status,400);assert.equal((await request('/api/bookings','POST',{...x,date:'2027-02-30'},{'Idempotency-Key':'test-invalid-0001'})).status,400);assert.equal((await request('/api/bookings','POST',x,{Origin:'https://evil.example','Idempotency-Key':'test-origin-0001'})).status,403);const headers={'Idempotency-Key':'test-booking-0001'};const r=await request('/api/bookings','POST',x,headers);assert.equal(r.status,201);const a=await r.json(),b=await (await request('/api/bookings','POST',x,headers)).json();assert.equal(a.id,b.id);assert.equal(app.state().bookings.length,1);const saved=JSON.parse(await readFile(path.join(dir,'state.json'),'utf8'));assert.equal(saved.bookings[0].phone,x.phone);const publicData=JSON.stringify(await (await request('/api/availability')).json());assert.ok(!publicData.includes(x.phone));assert.equal((await request('/.runtime/state.json')).status,404);});
test('two simultaneous confirmations cannot take the same venue and day',async t=>{const {request}=await setup(t);const x=booking();const a=await (await request('/api/bookings','POST',x,{'Idempotency-Key':'booking-first-0001'})).json();const b=await (await request('/api/bookings','POST',x,{'Idempotency-Key':'booking-second-0001'})).json();const auth={Authorization:'Bearer test-only'};const results=await Promise.all([request('/api/admin/bookings','PATCH',{id:a.id,status:'confirmed'},auth),request('/api/admin/bookings','PATCH',{id:b.id,status:'confirmed'},auth)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const busy=await (await request('/api/availability')).json();assert.equal(busy.unavailable.length,1);assert.equal((await request('/api/bookings','POST',x,{'Idempotency-Key':'booking-third-0001'})).status,409);assert.equal((await request('/api/bookings','POST',{...x,venue:seed.venues[1].id},{'Idempotency-Key':'booking-other-0001'})).status,201);});
test('Telegram invitations require activation and notify multiple recipients',async t=>{let updates=[],sent=[],number=1;const fetcher=async(url,opts)=>{const method=url.split('/').at(-1),args=JSON.parse(opts.body);let result;if(method==='getMe')result={username:'test_les_bot'};else if(method==='getUpdates'){result=updates.filter(u=>u.update_id>=args.offset);}else if(method==='sendMessage'){sent.push(args);result={message_id:number++};}else throw Error('Unexpected external request');return new Response(JSON.stringify({ok:true,result}),{status:200});};const {request,app}=await setup(t,{botToken:'test-only-not-real',fetcher});const auth={Authorization:'Bearer test-only'};for(let i=1;i<=2;i++){const invite=await (await request('/api/admin/invite','POST',{},auth)).json();const code=new URL(invite.url).searchParams.get('start');updates.push({update_id:i,message:{text:'/start '+code,chat:{id:i,type:'private'},from:{first_name:'Test '+i,username:'test'+i}}});await request('/api/admin/telegram/sync','POST',{},auth);}const list=await (await request('/api/admin/telegram','GET',null,auth)).json();assert.equal(list.recipients.length,2);assert.ok(list.recipients.every(r=>!r.enabled));for(const r of list.recipients)await request('/api/admin/telegram','PATCH',{id:r.id,enabled:true},auth);await request('/api/bookings','POST',booking(),{'Idempotency-Key':'telegram-book-0001'});await app.tick();assert.equal(sent.length,2);assert.deepEqual(sent.map(x=>x.chat_id).sort(),['1','2']);await app.tick();assert.equal(sent.length,2);});
