import {cp,readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {layout,pages,filenames} from '../dist/assets/render.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
const content=JSON.parse(await readFile(path.join(root,'dist/data/content.json'),'utf8'));
await mkdir(path.join(root,'dist'),{recursive:true});
for(const p of pages)await writeFile(path.join(root,'dist',filenames[p]),layout(content,p));
for(const file of await readdir(path.join(root,'dist')))if(file.endsWith('.html'))await cp(path.join(root,'dist',file),path.join(root,file));
await cp(path.join(root,'dist','assets'),path.join(root,'assets'),{recursive:true});
await cp(path.join(root,'dist','data'),path.join(root,'data'),{recursive:true});
await writeFile(path.join(root,'.nojekyll'),'');
console.log(`Built ${pages.length} pages in dist/ and mirrored the GitHub Pages version`);
